// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"github.com/KouT127/gin-sample/backend/domain/model"
)

type Connection interface {
	IsConnection()
}

type Edge interface {
	IsEdge()
}

type Node interface {
	IsNode()
}

type AddTaskPayload struct {
	ClientMutationID *string     `json:"clientMutationId"`
	Task             *model.Task `json:"task"`
}

type AddUserPayload struct {
	ClientMutationID *string     `json:"clientMutationId"`
	User             *model.User `json:"user"`
}

type TaskInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
}

type UserInput struct {
	Name   string `json:"name"`
	Gender string `json:"gender"`
}
