// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type NewTask struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
}

type NewUser struct {
	Name   string `json:"name"`
	Gender string `json:"gender"`
}
